[package]
name = "tyrosine-common"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "4.2.0"
rand = "0.8.5"
sorted-vec = "0.8.3"
